include: package:flutter_lints/flutter.yaml

linter:
  rules:
    unnecessary_brace_in_string_interps: false
    prefer_interpolation_to_compose_strings: false
    non_constant_identifier_names: false
    prefer_conditional_assignment: false
#     avoid_print: false
#     prefer_const_constructors_in_immutables: false
#     prefer_const_constructors: false
#     prefer_const_literals_to_create_immutables: false
#     prefer_final_fields: false
#     unnecessary_breaks: true
#     use_key_in_widget_constructors: false

# Alternatively: ignore_for_file: non_constant_identifier_names, prefer_conditional_assignment